### ISSUE TITLE
Problem with compiling.

### ISSUE THREAD

**Issue by PeterBorisenko** [brbx/libusb-d#1]
I've got a several errors:

```
        module core.sys.posix.sys.time import 'timeval' not found
```

if I change import core.sys.posix.sys.time : timeval; to
import std.socket : timeval; I see this:

```
         module consts is in file 'consts.d' which cannot be read
```

**Comment by rlonstein** [comment]
What version of the D compiler? What platform (Windows, Linux) and release?

**Comment by rlonstein** [comment]
Also for v2.0.67, brbx/libusb-d#2

**Comment by PeterBorisenko** [comment]
Platform is Windows 7 32bit. D compiler is dmd v2.066.1.

**Comment by rlonstein** [comment]
I'm afraid I don't have Win7. I work on Posix-like systems (OSX, Linux). I'll see if I can do anything with WinXP and VC2010-Express but it's not a platform I use.

**Comment by PeterBorisenko** [comment]
Ok. I'll try to fix it somehow.

**Comment by rlonstein** [comment]
You might try this diff: https://gist.github.com/rlonstein/bb24b8d6e668f39ec63c to fix the import. I don't have a way to test it, but it should bring in the correct symbols. The missing `consts.d` I think is something peculiar about your compilation, it works here in the `examples/` and in a couple of in-house projects. Assuming you're using `dub`, show me your `dub.json` and the output from `dub -v build -f` or similar from your build.

**Comment by rlonstein** [comment]
@Disgust any follow up to my gist and collecting output?

**Comment by Disgust** [comment]
This is my dub.json:

    {
        "name": "rom-prog",
        "description": "A minimal D application.",
        "copyright": "Copyright © 2015, Peter Borisenko",
        "authors": ["Peter Borisenko"],
        "dependencies": {
            "dlangui": "~master",
            "libusb-d": "~>0.1.0"
        }
    }


I've making changes  like in your gist but don't have winsock2.d module.
dmd version is 2.066.1

**Comment by PeterBorisenko** [comment]
I don't have winsock2.d module in /core/sys/windows
dmd version is 2.066.1
dub.json is 
{
    "name": "rom-prog",
    "description": "A minimal D application.",
    "copyright": "Copyright © 2015, Peter Borisenko",
    "authors": ["Peter Borisenko"],
    "dependencies": {
        "dlangui": "~master",
        "libusb-d": "~>0.1.0"
    }
}

**Comment by rlonstein** [comment]
Okay, I see it was committed Dec 2014, https://github.com/D-Programming-Language/druntime/commits/master/src/core/sys/windows/winsock2.d, and isn't in a tagged release before 2.067. I'm afraid you're stuck if you can't update to the current runtime. You might copy the necessary definition (it's a few lines) into your own source tree as a work around.

**Comment by rlonstein** [comment]
Closed for lack of response.
